workflows:
  android-apk-build:
    name: Build Android APK (Simple)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: 20
      java: 17
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: | 
          npm install --legacy-peer-deps
          # نصب ابزارهای جدید و حذف ابزار قدیمی برای جلوگیری از تداخل
          npm install @react-native/metro-config@0.75.4 @react-native/babel-preset@0.75.4 --save-dev
          npm uninstall metro-react-native-babel-preset
      - name: Auto-Fix Config Files
        script: |
          # بازنویسی خودکار تنظیمات بابل و مترو با استاندارد نسخه 0.75
          echo "module.exports = { presets: ['module:@react-native/babel-preset'] };" > babel.config.js
          echo "const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config'); module.exports = mergeConfig(getDefaultConfig(__dirname), {});" > metro.config.js
      - name: Build Android APK
        script: | 
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk