workflows:
  android-apk-build:
    name: Build Android APK (Simple)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: 20
      java: 17
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: | 
          npm install --legacy-peer-deps
          npm install @react-native/gradle-plugin@0.75.4 --no-save
          # این خط برای رفع خطای Metro اضافه شده است
          npm install @react-native/metro-config --no-save
      - name: Build Android APK
        script: | 
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk